## 4.2.2 Evaluating a regression model

1 R^2  or coefficient of determination
2 Mean absolute error
3 Mean squared error

## R^2

What R squared does : Compares your models predictions to the mean of the targets.Values can range from negatvie infiinity ( a very poor model) t1.For example ,if all your model does is predict the mean of the targets ,its r^2 value would be zero .And if your model perfectly predicts a range of numbers its r^2 value would be 1.

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# Import boston housing dataset
from sklearn.datasets import load_boston
boston = load_boston()
boston;

boston_df = pd.DataFrame(boston["data"],columns = boston ["feature_names"])
boston_df["target"]=pd.Series(boston["target"])
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [7]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

np.random.seed(42)

X= boston_df.drop("target",axis=1)
Y= boston_df["target"]

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)
model = RandomForestRegressor()

model.fit(X_train,Y_train);

In [8]:
model.score(X_test,Y_test)

0.873969014117403

In [13]:
from sklearn.metrics import r2_score 

Y_test_mean = np.full (len(Y_test),Y_test.mean())


## fill an array with y_test  mean 

In [15]:
Y_test.mean()

21.488235294117644

In [17]:
r2_score(Y_test,Y_test_mean)

0.0

In [18]:
r2_score(Y_test,Y_test)

1.0

## Mean absolute error 


In [20]:
from sklearn.metrics import mean_absolute_error

Y_preds = model.predict(X_test)

mae = mean_absolute_error(Y_test,Y_preds)
mae

2.1226372549019623

In [24]:
df = pd.DataFrame(data={"actual data": Y_test,
                       "predicted data": Y_preds })
df["differences"]= df["predicted data"] - df["actual data"]
df

actual data  predicted data  differences
173         23.6          23.002       -0.598
274         32.4          30.826       -1.574
491         13.6          16.734        3.134
72          22.8          23.467        0.667
452         16.1          16.853        0.753
..           ...             ...          ...
412         17.9          13.030       -4.870
436          9.6          12.490        2.890
411         17.2          13.406       -3.794
86          22.5          20.219       -2.281
75          21.4          23.898        2.498

[102 rows x 3 columns]

## Mean squared error

In [25]:
from sklearn.metrics import mean_squared_error

Y_preds = model.predict(X_test)

mse = mean_squared_error(Y_test,Y_preds)
mse

9.242328990196082

## 4.2.3 Using the scoring parameter

In [27]:
heart_disease= pd.read_csv("data/original.csv")

In [28]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)
X=heart_disease.drop("target",axis=1)
Y=heart_disease["target"]

clf= RandomForestClassifier()

In [33]:
np.random.seed(42)

cv_acc= cross_val_score(clf,X,Y,cv=5, scoring=None)
cv_acc

array([0.81967213, 0.90163934, 0.83606557, 0.78333333, 0.78333333])

In [34]:
#Cross-validated accuracy
print(f'The cross-validated accuracy is: {np.mean(cv_acc)*100: 2f}%')

The cross-validated accuracy is:  82.480874%


In [41]:
#Precision
cv_pre= cross_val_score(clf,X,Y,cv=5, scoring= "precision")
cv_pre

array([0.78947368, 0.90625   , 0.82758621, 0.8125    , 0.76315789])

In [42]:
#Recall

cv_rec= cross_val_score(clf,X,Y,cv=5, scoring= "recall")
cv_rec

array([0.87878788, 0.87878788, 0.84848485, 0.81818182, 0.87878788])

In [49]:
## Now with a regression model 

from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)
X= boston_df.drop("target",axis =1)
Y= boston_df["target"]

clf=RandomForestRegressor()
np.random.seed(42)
cv_r2 = cross_val_score(clf,X,Y,cv=5,scoring = None)

np.mean(cv_r2)


0.622375083951403

In [51]:
np.random.seed(42)

cv_r2 = cross_val_score(clf,X,Y,cv=5,scoring ="r2")


In [52]:
np.random.seed(42)

cv_r2 = cross_val_score(clf,X,Y,cv=5,scoring ="neg_mean_absolute_error") 

### 4.3 Using different evaluation metrics as scikit-learn functions

In [67]:
## Classification evaluation functions
from sklearn.metrics import accuracy_score,precision_score,f1_score,recall_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X= heart_disease.drop("target",axis=1)
Y=heart_disease["target"]

clf=RandomForestClassifier()

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

clf.fit(X_train,Y_train)

Y_pred = clf.predict(X_test)

print("Classifier metrics on the test set")
print(f"Accuracy of the model is : {accuracy_score(Y_test,Y_pred)*100: .2f}%")
print(f"Precision score of the model is : {precision_score(Y_test,Y_pred)}")
print(f"Recall : {recall_score(Y_test,Y_pred)}")
print(f"f1_score : {f1_score(Y_test,Y_pred)}")

Classifier metrics on the test set
Accuracy of the model is :  81.97%
Precision score of the model is : 0.7941176470588235
Recall : 0.8709677419354839
f1_score : 0.8307692307692308


**Regression evaluation functions**

In [73]:
from sklearn.metrics import r2_score, mean_absolute_error,mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

np.random.seed(42)

X=boston_df.drop("target",axis=1)
Y=boston_df["target"]


model=RandomForestRegressor()

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size = 0.2)

model.fit(X_train,Y_train)

Y_pred= model.predict(X_test)

print("Regressor metrics on the test set")
print(f"R2_score is  : {r2_score(Y_test,Y_pred)}")
print(f"mean_absolute_error is  : {mean_absolute_error(Y_test,Y_pred)}")
print(f"mean_squared_error is  : {mean_squared_error(Y_test,Y_pred)}")

Regressor metrics on the test set
R2_score is  : 0.8739690141174031
mean_absolute_error is  : 2.1226372549019623
mean_squared_error is  : 9.242328990196082
