<a href="https://colab.research.google.com/github/Aahra/Jupyter_notebook_projects/blob/master/Intro_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np

#Datatypes and Attributes

In [19]:
#Numpy main datatype is ndarray - stands  for n-dimensional array

In [20]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [21]:
type(a)

numpy.ndarray

In [22]:
b=np.array([[1,2,3,4],
            [6,7,8,9]])
b

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [23]:
#Attribute

In [24]:
a.shape

(3,)

In [25]:
b.shape

(2, 4)

In [26]:
a.ndim,b.ndim

(1, 2)

In [27]:
a.dtype

dtype('int64')

In [28]:
b.dtype

dtype('int64')

In [29]:
a.size,b.size

(3, 8)

In [30]:
type(b)

numpy.ndarray

#Create a Dataframe from  Numpy Array

In [31]:
import pandas as pd

df = pd.DataFrame(a)
df

0
0  1
1  2
2  3

In [32]:
df2 = pd.DataFrame(b)
df2

0  1  2  3
0  1  2  3  4
1  6  7  8  9

#Creating arrays

In [33]:
sample_array= np.array([1,2,3])
sample_array

array([1, 2, 3])

In [34]:
sample_array.dtype

dtype('int64')

In [35]:
type(sample_array)

numpy.ndarray

In [39]:
ones= np.ones((1,2))
ones

array([[1., 1.]])

In [44]:
ones=np.ones((1,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [48]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [50]:
random_array= np.random.randint(0,10,size=(2,3))
random_array

array([[7, 5, 4],
       [3, 1, 4]])

In [51]:
random_array.size

6

In [52]:
random_array.shape

(2, 3)

In [59]:
random_array_2=np.random.random((3,5))
random_array_2

array([[0.49015098, 0.73724438, 0.12758161, 0.58659055, 0.79645935],
       [0.04339372, 0.69944459, 0.89645931, 0.20240917, 0.88699455],
       [0.00098539, 0.25441448, 0.10230762, 0.90750944, 0.14570903]])

In [54]:
random_array_2.shape

(3, 5)

In [55]:
random_array_2.size

15

In [60]:
random_array_3= np.random.rand(3,5)
random_array_3

array([[0.3561686 , 0.91185017, 0.67560516, 0.62264555, 0.19633614],
       [0.6604626 , 0.78425542, 0.32138956, 0.53552717, 0.1712175 ],
       [0.73050582, 0.21106981, 0.67959083, 0.21612607, 0.33507431]])

In [65]:
#pseudo random number

#np.random.seed(0)

In [78]:
np.random.seed(99999)
random_array_4= np.random.randint(10,size=(3,5))
random_array_4

array([[0, 3, 1, 8, 1],
       [3, 8, 5, 6, 0],
       [6, 0, 4, 0, 9]])

In [82]:
random_array_4

array([[0, 3, 1, 8, 1],
       [3, 8, 5, 6, 0],
       [6, 0, 4, 0, 9]])

In [41]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]]])