<a href="https://colab.research.google.com/github/Aahra/Jupyter_notebook_projects/blob/master/Intro_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

#1 .Datatypes and Attributes

In [3]:
#Numpy main datatype is ndarray - stands  for n-dimensional array

In [4]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [6]:
b=np.array([[1,2,3,4],
            [6,7,8,9]])
b

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [7]:
#Attribute

In [8]:
a.shape

(3,)

In [9]:
b.shape

(2, 4)

In [10]:
a.ndim,b.ndim

(1, 2)

In [11]:
a.dtype

dtype('int64')

In [12]:
b.dtype

dtype('int64')

In [13]:
a.size,b.size

(3, 8)

In [14]:
type(b)

numpy.ndarray

#2. Create a Dataframe from  Numpy Array

In [15]:
import pandas as pd

df = pd.DataFrame(a)
df

0
0  1
1  2
2  3

In [16]:
df2 = pd.DataFrame(b)
df2

0  1  2  3
0  1  2  3  4
1  6  7  8  9

#Creating arrays

In [17]:
sample_array= np.array([1,2,3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int64')

In [19]:
type(sample_array)

numpy.ndarray

In [20]:
ones= np.ones((1,2))
ones

array([[1., 1.]])

In [21]:
ones=np.ones((1,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [22]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array= np.random.randint(0,10,size=(2,3))
random_array

array([[0, 7, 8],
       [6, 8, 7]])

In [24]:
random_array.size

6

In [25]:
random_array.shape

(2, 3)

In [26]:
random_array_2=np.random.random((3,5))
random_array_2

array([[0.60779134, 0.79565375, 0.67302702, 0.12680375, 0.05792007],
       [0.99075033, 0.25055154, 0.95500183, 0.76870687, 0.70493759],
       [0.64909808, 0.29674565, 0.89447657, 0.14062777, 0.46363934]])

In [27]:
random_array_2.shape

(3, 5)

In [28]:
random_array_2.size

15

In [29]:
random_array_3= np.random.rand(3,5)
random_array_3

array([[0.22038816, 0.22258426, 0.67187897, 0.13195311, 0.63652   ],
       [0.81979831, 0.44203948, 0.58373607, 0.88712499, 0.11257386],
       [0.00880054, 0.69012311, 0.55948329, 0.77014579, 0.63344328]])

In [30]:
#pseudo random number

#np.random.seed(0)

In [31]:
np.random.seed(99999)
random_array_4= np.random.randint(10,size=(3,5))
random_array_4

array([[0, 3, 1, 8, 1],
       [3, 8, 5, 6, 0],
       [6, 0, 4, 0, 9]])

In [32]:
random_array_4

array([[0, 3, 1, 8, 1],
       [3, 8, 5, 6, 0],
       [6, 0, 4, 0, 9]])

#3. Viewing arrays and matrices

In [34]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [36]:
df3 = pd.DataFrame(random_array_4)
df3

0  1  2  3  4
0  0  3  1  8  1
1  3  8  5  6  0
2  6  0  4  0  9

In [37]:
b[1]

array([6, 7, 8, 9])

In [38]:
b[0]

array([1, 2, 3, 4])

In [33]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]]])